// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiApp.Data;

namespace WebApiApp.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20221027073919_AddTBLoaiHH")]
    partial class AddTBLoaiHH
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiApp.Data.HangHoa", b =>
                {
                    b.Property<Guid>("MaHH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<byte>("GiamGia")
                        .HasColumnType("tinyint");

                    b.Property<int?>("MaLoaiHH")
                        .HasColumnType("int");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaHH");

                    b.HasIndex("MaLoaiHH");

                    b.ToTable("HangHoa");
                });

            modelBuilder.Entity("WebApiApp.Data.LoaiHH", b =>
                {
                    b.Property<int>("MaLoaiHH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TenLoaiHH")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("MaLoaiHH");

                    b.ToTable("LoaiHH");
                });

            modelBuilder.Entity("WebApiApp.Data.HangHoa", b =>
                {
                    b.HasOne("WebApiApp.Data.LoaiHH", "Loai")
                        .WithMany("HangHoas")
                        .HasForeignKey("MaLoaiHH");

                    b.Navigation("Loai");
                });

            modelBuilder.Entity("WebApiApp.Data.LoaiHH", b =>
                {
                    b.Navigation("HangHoas");
                });
#pragma warning restore 612, 618
        }
    }
}
